
modLoader="javafml"

loaderVersion="[35,)"

license="All rights reserved"

[[mods]]

modId="forgetutorial"

version="1.0"

displayName="Forge Tutorial"

displayURL=""

logoFile="examplemod.png"

credits="TurtyWurty - Tutorial giver"

authors="Croizzant"

description='''
It's a tutorial lel
'''
